### ISSUE TITLE
Fiks at kortstokken resettes om man vinner og hopper tilbake

### ISSUE THREAD

**Issue by Sardtok** [Sardtok/adventur-casino#5]
Hvis man vinner ved å legge kort i forskjellige hauger, resettes kortstokken om man hopper tilbake til starten av spillet.

**Comment by emiltayl** [comment]
Hva med å matche "flash-prose"-elementer med /Tiden spinner/ før man resetter? Jeg tror det skal funke bortsett fra i de tilfellene man gjør ferdig et spill uten å vinne noe.

**Comment by Sardtok** [comment]
Det fikk meg for så vidt til å tenke. Kan ta det på at man har en revertert handling. Disse merkes med CSS-klassen reverted.
